---

version: "3"
services:
  website:
    container_name: website
    build:
      context: .
    volumes:
      - .:/code
      - node_modules:/code/node_modules
    ports:
      - 8000:8000

volumes:
  node_modules:
